### Auth0testing
# @name loginusingAuth0
POST https://dev-htjrdxyu2p87zjsm.us.auth0.com/oauth/token
content-type: application/json

{"client_id":"NexMV3Aglp9w1rODmxjbZDFxzaJ17vCO","client_secret":"c_vQ1c-Du9V92YC6iYBoORZtXE23KquJJ8Iz8wnifXaMVRPjjPKLXSZupY7B9cs_","audience":"books","grant_type":"client_credentials"}



###
GET http://localhost:3000/books
Authorization: Bearer {{loginusingAuth0.response.body.access_token}}



###
GET http://localhost:3000/books
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImRHSzA3emppWk1EZnRvOWJmVmZtbiJ9.eyJpc3MiOiJodHRwczovL2Rldi1odGpyZHh5dTJwODd6anNtLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDExMTg4Mzg5NDY1MjUyODU0ODQ1NyIsImF1ZCI6WyJib29rcyIsImh0dHBzOi8vZGV2LWh0anJkeHl1MnA4N3pqc20udXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY2OTgwMjQ0MywiZXhwIjoxNjY5ODg4ODQzLCJhenAiOiJwWFFlR1haNnp1OE9zcEMyeWQwSUZwNU5aZ1FrMjB0QyIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwifQ.ffK5gxkjzv7O24wM4AUggt0Oyhbzq-dajRB5yBgPiu2caCKzIvP8fPLrr_VQnZa9TLoTsqAKvQ-2werYpRQFD8C_yEj_ZL3p2hz3gK8qCHRoa6x8M1sBio0iw6vRMXbUdCKRy2XxdxUAz2BMk3nBZPDuOXm2zxcudpIXwEqjdDkcdMm083iTU39_u2gBkBavBilxx3f_0zTHoRJg0d7424E43AXR88dXsyPSqSFtNsYiUPHWG5W5XRl9J8Dy_ilgWz9jnPksuUT4PqyL4cN00qv5RSzkEtBec4gTBKleQySJYLsmEnqSvBD5WKi-4gdxnEDcYv2g6-SRmt2htFyZqw



###
GET http://localhost:3000/books
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImRHSzA3emppWk1EZnRvOWJmVmZtbiJ9.eyJpc3MiOiJodHRwczovL2Rldi1odGpyZHh5dTJwODd6anNtLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDExMTg4Mzg5NDY1MjUyODU0ODQ1NyIsImF1ZCI6WyJib29rcyIsImh0dHBzOi8vZGV2LWh0anJkeHl1MnA4N3pqc20udXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY2OTgwMjQ0MywiZXhwIjoxNjY5ODg4ODQzLCJhenAiOiJwWFFlR1haNnp1OE9zcEMyeWQwSUZwNU5aZ1FrMjB0QyIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwifQ.ffK5gxkjzv7O24wM4AUggt0Oyhbzq-dajRB5yBgPiu2caCKzIvP8fPLrr_VQnZa9TLoTsqAKvQ-2werYpRQFD8C_yEj_ZL3p2hz3gK8qCHRoa6x8M1sBio0iw6vRMXbUdCKRy2XxdxUAz2BMk3nBZPDuOXm2zxcudpIXwEqjdDkcdMm083iTU39_u2gBkBavBilxx3f_0zTHoRJg0d7424E43AXR88dXsyPSqSFtNsYiUPHWG5W5XRl9J8Dy_ilgWz9jnPksuUT4PqyL4cN00qv5RSzkEtBec4gTBKleQySJYLsmEnqSvBD5WKi-4gdxnEDcYv2g6-SRmt2htFyZqw



### login
# @name loginUsingAuthLocal
POST http://localhost:3000/auth/local HTTP/1.1
content-type: application/json

{ "username": "use4",
"password" : "password1"}



###
### POST Request for a book with just a title
## expeted result 201 Created with the id of the book in location and a book returned.
POST http://localhost:3000/books HTTP/1.1
content-type: application/json
Authorization: Bearer {{loginUsingAuthLocal.response.body.accesstoken}}

{ "title" : "a new book from an authenciated"}

###
### POST Request for a book with just a title
## expeted result 201 Created with the id of the book in location and a book returned.
POST http://localhost:3000/books HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlNCIsImlhdCI6MTY2NjcxNTY5NCwiZXhwIjoxNjY2NzE1OTk0fQ.WWfuNSzYxr2bENiJwPpfDovFMObpQ0KmHXbBTxOPR20

{ "title" : "a really new book"}


###
### POST Request for a book with no title -
## 400 with some JOI details inculding the title is required
POST http://localhost:3000/books HTTP/1.1
content-type: application/json



{ "year_written": 2022}

###
### POST Request for a book with a title - but a string for a year - this should fail
## 400 with a message about year_written not being a number
POST http://localhost:3000/books HTTP/1.1
content-type: application/json

{ "year_written": "this year",
"title" : "The BEST"}

###
# comment goes here - will fail with 404 as on collection

PUT http://localhost:3000/books/63340cde5def8f9f17677bd8 HTTP/1.1
content-type: application/json

{ "year_written": 2036,
"title" : "2035"}

