### Auth0testing
# @name loginusingAuth0
POST https://dev-htjrdxyu2p87zjsm.us.auth0.com/oauth/token
content-type: application/json

{"client_id":"NexMV3Aglp9w1rODmxjbZDFxzaJ17vCO","client_secret":"c_vQ1c-Du9V92YC6iYBoORZtXE23KquJJ8Iz8wnifXaMVRPjjPKLXSZupY7B9cs_","audience":"books","grant_type":"client_credentials"}



###
GET http://localhost:3000/books
Authorization: Bearer {{loginusingAuth0.response.body.access_token}}



###
GET http://localhost:3000/books
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImRHSzA3emppWk1EZnRvOWJmVmZtbiJ9.eyJpc3MiOiJodHRwczovL2Rldi1odGpyZHh5dTJwODd6anNtLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJOZXhNVjNBZ2xwOXcxck9EbXhqYlpERnh6YUoxN3ZDT0BjbGllbnRzIiwiYXVkIjoiYm9va3MiLCJpYXQiOjE2Njk4MDA0MzYsImV4cCI6MTY2OTg4NjgzNiwiYXpwIjoiTmV4TVYzQWdscDl3MXJPRG14amJaREZ4emFKMTd2Q08iLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.S_2UhRuAK7jYsqV8zbgF0wqY_Av2LDQEm2VdLg-5Gj4_rV7CQTEy6Bc_07VwVrB1kVMC0fKwACtHkfLa8nnPBoFrfXeCfE304BKldf8lAmYWXisa6Ahet2L8rcHM9m6RZasRFkO-Xhd9VorXdlm2-G4Q-PS7x-d1vjRKebQIyR9tfYrIqoDXgaAq1oOYMplLN95Ot8B0rD5YwxkNwizgmKQTScZoIq5NYDkVv4J0OGQf4nCDg5IwGgbyMhouJySnNzPrEh6OMsJx3wFxi8eNd7SIeCPgJeA8HdCbqDrtUBLBAdepaNqPTRVLn7OrhIgQTd5AW1A8dD3w8x53QwA_Tw






### login
# @name loginUsingAuthLocal
POST http://localhost:3000/auth/local HTTP/1.1
content-type: application/json

{ "username": "use4",
"password" : "password1"}



###
### POST Request for a book with just a title
## expeted result 201 Created with the id of the book in location and a book returned.
POST http://localhost:3000/books HTTP/1.1
content-type: application/json
Authorization: Bearer {{loginUsingAuthLocal.response.body.accesstoken}}

{ "title" : "a new book from an authenciated"}

###
### POST Request for a book with just a title
## expeted result 201 Created with the id of the book in location and a book returned.
POST http://localhost:3000/books HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlNCIsImlhdCI6MTY2NjcxNTY5NCwiZXhwIjoxNjY2NzE1OTk0fQ.WWfuNSzYxr2bENiJwPpfDovFMObpQ0KmHXbBTxOPR20

{ "title" : "a really new book"}


###
### POST Request for a book with no title -
## 400 with some JOI details inculding the title is required
POST http://localhost:3000/books HTTP/1.1
content-type: application/json



{ "year_written": 2022}

###
### POST Request for a book with a title - but a string for a year - this should fail
## 400 with a message about year_written not being a number
POST http://localhost:3000/books HTTP/1.1
content-type: application/json

{ "year_written": "this year",
"title" : "The BEST"}

###
# comment goes here - will fail with 404 as on collection

PUT http://localhost:3000/books/63340cde5def8f9f17677bd8 HTTP/1.1
content-type: application/json

{ "year_written": 2036,
"title" : "2035"}

